### ISSUE TITLE
Limit logging based on disk space 

### ISSUE THREAD

**Issue by mdmillerii** [openbmc/phosphor-event#16]
Instead of adding the number of bytes in each file look at the space consumed in the file system.

Storage capacity is the limit motivation not network or console display time.

Instead of opening each file for append and calling ftellg on the iostream use the stat syscall to find disk space used.  Also this is 1 system call not 3-4 (open, seek, 2nd seek? close) and requires less memory allocations and setup.

**Comment by anoo1** [comment]
Being fixed with https://github.com/openbmc/phosphor-event/pull/17

**Comment by williamli80** [comment]
Hi. What is the update? https://github.com/openbmc/phosphor-event/pull/17

**Comment by anoo1** [comment]
Merged. Available under tag v0.8.
